apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    topology: appscluster
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: website
  namespace: demo
  labels:
    topology: appscluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapi
  namespace: demo
  labels:
    topology: appscluster
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: demo
  labels:
    topology: appscluster
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: webapi-allow-website
  namespace: demo
  labels:
    topology: appscluster
spec:
  selector:
    matchLabels:
      app: webapi
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/demo/sa/website
---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: demo
  labels:
    topology: appscluster
    app: website
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: demo
  labels:
    topology: appscluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      serviceAccountName: website
      containers:
      - name: website
        image: binarydad/website
        env:
        - name: WEBAPI_URL
          value: webapi
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  namespace: demo
  labels:
    topology: appscluster
    app: webapi
    istio.io/global: "true"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-v1
  namespace: demo
  labels:
    topology: appscluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
      version: v1
  template:
    metadata:
      labels:
        app: webapi
        version: v1
    spec:
      serviceAccountName: webapi
      containers:
      - name: webapi
        image: binarydad/webapi
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    topology: servicescluster
    istio.io/dataplane-mode: ambient
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapi
  namespace: demo
  labels:
    topology: servicescluster
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: demo
  labels:
    topology: servicescluster
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: webapi-allow-website
  namespace: demo
  labels:
    topology: servicescluster
spec:
  selector:
    matchLabels:
      app: webapi
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/demo/sa/website
---
apiVersion: v1
kind: Service
metadata:
  name: webapi
  namespace: demo
  labels:
    topology: servicescluster
    app: webapi
    istio.io/global: "true"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-v2
  namespace: demo
  labels:
    topology: servicescluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
      version: v2
  template:
    metadata:
      labels:
        app: webapi
        version: v2
    spec:
      serviceAccountName: webapi
      containers:
      - name: webapi
        image: binarydad/webapi
        ports:
        - containerPort: 80
        resources: {}